---
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly

allow_failures:
  - php: nightly
  - php: hhvm-nightly

notifications:
  email: false

before_install:
  - curl -s http://getcomposer.org/installer | php

install:
  - php composer.phar install

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text
